[[pages]]
path = "pages/fifa/agent.py"
name = "ä»£ç†äºº"
icon = "âš½ï¸"

[[pages]]
path = "pages/fifa/vision_2020.py"
name = "FIFAãƒ“ã‚¸ãƒ§ãƒ³2020-2023"
icon = "ğŸ‘€"

[[pages]]
path = "pages/fifa/football_law.py"
name = "FOOTBALL LAW ANNUAL REVIEW"
icon = "âš–ï¸"
